[package]
name = "smart-hive"
version = "0.1.0"
edition = "2024"

[dependencies]
software-defined-hive = { path = "../software-defined-hive" }
hardware-abstraction = { path = "../hardware-abstraction" }
esp-idf-svc = "0.48"
esp-idf-hal = "0.43"
esp-idf-sys = "0.34"
