[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = ".cargo/ldproxy-wrapper.sh"

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = { value = "v5.1" }
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults" }