[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
rustflags = [
    "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = { value = "v5.1" }
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults" }
# Tell ldproxy which linker to use
ESP_IDF_TOOLS_INSTALL_DIR = { value = "global" }