[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
rustflags = [
    "-C", "link-arg=--ldproxy-linker",
    "-C", "link-arg=xtensa-esp32-elf-gcc",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = { value = "v5.1" }
ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults"